### ISSUE TITLE
Promise Rejection Issue

### ISSUE THREAD

**Issue by bkhoward2001** [HashLips/generative-art-opensource#114]
I am getting the following error and need some help:

PS E:\NTF\generative-art-opensource-3> node index.js
(node:6436) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'layers' of undefined
    at createDna (E:\NTF\generative-art-opensource-3\index.js:119:17)
    at startCreating (E:\NTF\generative-art-opensource-3\index.js:148:18)
    at Object.<anonymous> (E:\NTF\generative-art-opensource-3\index.js:180:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

Not sure how to fix... I am not an experienced coder. Thank you.

**Comment by Ponda1** [comment]
Refer to issue #38

**Comment by bkhoward2001** [comment]
I am using version 3....

**Comment by tobeliten** [comment]
> I am using version 3....

did you find a solution?

**Comment by bkhoward2001** [comment]
> > I am using version 3....
> 
> did you find a solution?

No not yet
