### ISSUE TITLE
Cant generate more then 10 images

### ISSUE THREAD

**Issue by Wanackon** [HashLips/generative-art-opensource#151]
Got this error:

creating NFT 1 of 9998
- rarity: undefined
(node:24260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at D:\Git\generative-art-opensource\index.js:133:77
    at Array.forEach (<anonymous>)
    at createDna (D:\Git\generative-art-opensource\index.js:132:11)
    at startCreating (D:\Git\generative-art-opensource\index.js:200:18)
    at Object.<anonymous> (D:\Git\generative-art-opensource\index.js:249:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dprodrick** [comment]
@Wanackon Check that each image in each of your layer contains the delimiter symbol you have set in your config.json.

So for example, in my config.json it looks like the following:

`const rarityDelimiter = "#";`

So in my case, I need to make sure that each image contains a #.

**Comment by Wanackon** [comment]
It fixed an issue. Thanks a lot.
