### ISSUE TITLE
PROBLEM:    version `GLIBC_2.25' not found (required by /lib/x86_64-linux-gnu/libuuid.so.1)

### ISSUE THREAD

**Issue by kandaris** [HashLips/generative-art-opensource#152]
When index.js is run the output is:

Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /lib/x86_64-linux-gnu/libuuid.so.1)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/todd/generative-art-opensource/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

System:

todd@anvil:~$ inxi -Sr
System:    Host: anvil Kernel: 5.4.0-84-generic x86_64 bits: 64 Desktop: Budgie 10.5.1 
           Distro: Ubuntu 20.04.3 LTS (Focal Fossa) 
Repos:     Active apt repos in: /etc/apt/sources.list 
           1: deb http://archive.ubuntu.com/ubuntu focal main restricted
           2: deb http://archive.ubuntu.com/ubuntu focal-updates main restricted
           3: deb http://archive.ubuntu.com/ubuntu focal universe
           4: deb http://archive.ubuntu.com/ubuntu focal-updates universe
           5: deb http://archive.ubuntu.com/ubuntu focal multiverse
           6: deb http://archive.ubuntu.com/ubuntu focal-updates multiverse
           7: deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           8: deb http://archive.ubuntu.com/ubuntu focal-security main restricted
           9: deb http://archive.ubuntu.com/ubuntu focal-security universe
           10: deb http://archive.ubuntu.com/ubuntu focal-security multiverse
           No active apt repos in: /etc/apt/sources.list.d/bitcoin-ubuntu-bitcoin-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/cybermax-dexter-ubuntu-sdl2-backport-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/git-core-ubuntu-ppa-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list 
           No active apt repos in: /etc/apt/sources.list.d/graphics-drivers-ubuntu-ppa-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/lutris-team-ubuntu-lutris-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list 
           No active apt repos in: /etc/apt/sources.list.d/nodesource.list 
           No active apt repos in: /etc/apt/sources.list.d/signal-xenial.list 
           No active apt repos in: /etc/apt/sources.list.d/teams.list 
           No active apt repos in: /etc/apt/sources.list.d/vscode.list 

Any help would be greatly appreciated.

**Comment by alexberendei** [comment]
Seems it's a problem when you install nodejs with snap. Try apt or manual install!
