### ISSUE TITLE
Node Index.js

### ISSUE THREAD

**Issue by alfriprata** [HashLips/generative-art-opensource#166]
I have problem with this code
Error: Cannot find module 'C:\Users\Fransiskus\Documents\Minting Dapps BSC\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
How to fix it?

**Comment by marcolivierbouch** [comment]
Hi! 

Got the same issue feel free to clone my fork! https://github.com/marcolivierbouch/generative-art-opensource

run command: `npm run generate`

Also i have this PR https://github.com/HashLips/generative-art-opensource/pull/167
