### ISSUE TITLE
Cannot read properties of 'Undefined'

### ISSUE THREAD

**Issue by Doughp** [HashLips/generative-art-opensource#175]
I am trying to make a collection and everytime I run Node Index.js this occurs

PS C:\Users\\OneDrive\Desktop\generative-art-opensource-3> node index.js
C:\Users\\OneDrive\Desktop\generative-art-opensource-3\index.js:119        
  _races[_race].layers.forEach((layer) => {
                ^

TypeError: Cannot read properties of undefined (reading 'layers')
    at createDna (C:\Users\\OneDrive\Desktop\generative-art-opensource-3\index.js:119:17)
    at startCreating (C:\Users\\OneDrive\Desktop\generative-art-opensource-3\index.js:148:18)
    at Object.<anonymous> (C:\Users\\OneDrive\Desktop\generative-art-opensource-3\index.js:180:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) 
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
PS C:\Users\\OneDrive\Desktop\generative-art-opensource-3> 

All the Layers in the 'Config' and the 'Directory' and the Folder itself all match up. I have no clue what this is, any help is appreciated. Thank you.

**Comment by Oubaluna** [comment]
Same Here, I'm scanning since so many time the name of folder+file in config.js but I don't find any error... :(
certainly there is one, I don't get what else it can be

EDIT : my mistake was I change the value of my race but not the calling one in "const races" ! I succeed to make it run 💯

**Comment by Dtrix1612** [comment]
Could you please release the fixed code here.

I didnt understand what you mean and got the same problem.

**Comment by Oubaluna** [comment]
TypeError: Cannot read properties of undefined (reading 'layers')

This error mean you have an error in defining your 'layers' and a name mismatch. 

Mine was that instead of skull I change only one of the 2 and that generate the error.

After I change it by the same name it was running ok. Hope that help.

```
const raceWeights = [
  {
    value: "skull",
    from: 1,
    to: editionSize,
  },
];

const races = {
  skull: {
    name: "skull",
    layers:
```
