### ISSUE TITLE
The program was working and now the error appears

### ISSUE THREAD

**Issue by PlanktongGG** [HashLips/generative-art-opensource#184]
![image](https://user-images.githubusercontent.com/96208511/146266819-7b37d868-ceed-493c-ad57-46b409b849d3.png)

hi!

I don't know what have happened, the code was working and I have generated images two times, but now, this error keeps appearing and I don't know how to solve it, I have tried all the possible solutions posted here...

C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'undefined'
    at setSource (C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\node_modules\canvas\index.js:23:10)
    at C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\index.js:72:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\index.js:71:10)
    at C:\Users\gonza\Desktop\GENERADOR\generative-art-opensource-3\index.js:154:29
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'undefined',
  syscall: 'fopen'
}

Thank you in advance.

**Comment by kukyasin** [comment]
Open main.js

```
const buildDir = `${basePath}/build`;
const layersDir = `${basePath}/layers`;
```

You can change this.

```
const buildDir = `./build`;
const layersDir = `./layers`;
```

**Comment by nyray23** [comment]
I resolved the issue ! Make sure there is atleast one image in each of your rarity (original, rare, super_rare) folders. The error message is displaying because those folders are null.

**Comment by dhahami** [comment]
I added placeholder images to all my empty folders, and I checked to make sure I have all my rarity folders with at least one image but I still am getting this error.

**Comment by egebhaskaya** [comment]
> Open main.js
> 
> ```
> const buildDir = `${basePath}/build`;
> const layersDir = `${basePath}/layers`;
> ```
> 
> You can change this.
> 
> ```
> const buildDir = `./build`;
> const layersDir = `./layers`;
> ```

THANK YOU!
