### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by harisu26** [HashLips/generative-art-opensource#220]
Hey there, anyone could help me with the error. somehow it stopped in the middle of generating the variations and it showed this error: 

Error: Unsupported image type
    at setSource (C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:23:10)
    at C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:185:27     
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:184:12)
    at C:\Users\User\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:368:31     
    at Array.forEach (<anonymous>)

**Comment by harisu26** [comment]
I have checked each file and make sure everything is in PNG but the error still happen from time to time
