### ISSUE TITLE
Error: ENOENT, No such file or directory

### ISSUE THREAD

**Issue by Tanjilh** [HashLips/generative-art-opensource#221]
I cant seem to get this to work. I tested it with 3 assets in each layer and it was fine. However now with a larger amount it does not work and gives me this error:

PS C:\hystericgoons\generative-art-opensource> node index.js
C:\hystericgoons\generative-art-opensource\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src)
            ^

Error: ENOENT, No such file or directory 'C:\hystericgoons\generative-art-opensource\input/background/blue.png'
    at setSource (C:\hystericgoons\generative-art-opensource\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\hystericgoons\generative-art-opensource\node_modules\canvas\lib\image.js:62:9)
    at C:\hystericgoons\generative-art-opensource\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\hystericgoons\generative-art-opensource\node_modules\canvas\index.js:23:10)
    at C:\hystericgoons\generative-art-opensource\index.js:72:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\hystericgoons\generative-art-opensource\index.js:71:10)
    at C:\hystericgoons\generative-art-opensource\index.js:154:29
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\hystericgoons\\generative-art-opensource\\input/background/blue.png',
  syscall: 'fopen'
}

**Comment by Tanjilh** [comment]
nvm i was dumb, misspelt the main folder 👎
