### ISSUE TITLE
Always fails on number 6

### ISSUE THREAD

**Issue by BlueM92** [HashLips/generative-art-opensource#54]
I always get an error as it attempts to produce the 6th NFT with this error even when changing number to produce 100 instead of 10, is there a fix for this? Thanks

creating NFT 6 of 10
- rarity: rare
- dna: --01-00----00--
C:\Users\this_\OneDrive\Desktop\generative-art-opensource-main\index.js:75
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read property 'path' of undefined
    at C:\Users\this_\OneDrive\Desktop\generative-art-opensource-main\index.js:75:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\this_\OneDrive\Desktop\generative-art-opensource-main\index.js:74:10)
    at C:\Users\this_\OneDrive\Desktop\generative-art-opensource-main\index.js:215:27
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\this_\OneDrive\Desktop\generative-art-opensource-main\index.js:214:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\Users\this_\OneDrive\Desktop\generative-art-opensource-main>

**Comment by BlueM92** [comment]
I have closed this i hadnt put all rarities correctly, my bad
