### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Skulletje** [HashLips/generative-art-opensource#58]
I did npm install then npm install truffle -g and when doing node index.js i get this error

TypeError: Cannot read property 'length' of undefined
    at D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:133:77
    at Array.forEach (<anonymous>)
    at createDna (D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:132:11)
    at startCreating (D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:200:18)
    at Object.<anonymous> (D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:249:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)

What did i do wrong

**Comment by Skulletje** [comment]
I'd like to add on the full length of the error code 


##################
# Generative Art
# - Create your NFT collection
##################

start creating NFTs.
-----------------
creating NFT 1 of 1000
- rarity: undefined
D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:133
    let num = Math.floor(Math.random() * layer.elementIdsForRarity[_rarity].length);
                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:133:77
    at Array.forEach (<anonymous>)
    at createDna (D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:132:11)
    at startCreating (D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:200:18)
    at Object.<anonymous> (D:\Ùsers\skull\Bureaublad\generative-art-opensource-main\index.js:249:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
PS D:\Ùsers\skull\Bureaublad\generative-art-opensource-main>

**Comment by Ponda1** [comment]
Refer to issue #28 which has now been closed
