### ISSUE TITLE
Changing editionSize will cause error in node.js

### ISSUE THREAD

**Issue by norasyeezys** [HashLips/generative-art-opensource#95]
I changed editionSize from 10 to 20, and I got this error. It works fine with 10.

##################
# Generative Art
# - Create your NFT collection
##################

start creating NFTs.
-----------------
creating NFT 1 of 20
- rarity: undefined
C:\[%directory]\generative-art-opensource-main\index.js:133
    let num = Math.floor(Math.random() * layer.elementIdsForRarity[_rarity].length);
                                                                            ^

TypeError: Cannot read properties of undefined (reading 'length')
    at C:\Users\daepi\Documents\Blockchain\generative-art-opensource-main\index.js:133:77
    at Array.forEach (<anonymous>)
    at createDna (C:\[%directory]\generative-art-opensource-main\index.js:132:11)
    at startCreating (C:\[%directory]\generative-art-opensource-main\index.js:200:18)
    at Object.<anonymous> (C:\[%directory]\generative-art-opensource-main\index.js:249:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)

**Comment by bgastaldo** [comment]
Same issue, been trying to figure it out

**Comment by EclecticDeviant** [comment]
Also been trying to hammer this one out.  Everytime I change the Edition Size beyond 11, it throws this error.  It does 11 and less, for me at least, without issue.

**Comment by WalkingEclipse** [comment]
I think I figured it out. 
Go to config.js 
Then to line 129: const editionSize = 10; 
Change the number to the total number of NFT's you want to generate.

Then make sure to adjust your rarities. 
You can do this starting on line 135 and ending on line 138: 
let rarityWeights = [
  addRarity('super_rare', 1, 1),
  addRarity('rare', 2, 5),
  addRarity('original', 5, 10)

Adjust the numbers so the rarities match the total number of NFT's you want to create. 

Let me know if this helps. I was running the code and it would only create 10 editions. After doing some digging I figured it out and was able to do 15 editions without an error.

**Comment by norasyeezys** [comment]
> I think I figured it out.
> Go to config.js
> Then to line 129: const editionSize = 10;
> Change the number to the total number of NFT's you want to generate.
> 
> Then make sure to adjust your rarities.
> You can do this starting on line 135 and ending on line 138:
> let rarityWeights = [
> addRarity('super_rare', 1, 1),
> addRarity('rare', 2, 5),
> addRarity('original', 5, 10)
> 
> Adjust the numbers so the rarities match the total number of NFT's you want to create.
> 
> Let me know if this helps. I was running the code and it would only create 10 editions. After doing some digging I figured it out and was able to do 15 editions without an error.

After playing with numbers, I got it to work.

**Comment by laygir** [comment]
@WalkingEclipse indeed that's the way to go.

The second and third parameters are from and to. Meaning the length of range that rarity should be applied. And the provided range lengths must match the value of `editionSize` set in the config otherwise will throw an error while generating the outputs.

For example;
```
const editionSize = 100;

let rarityWeights = [
  addRarity('super_rare', 1, 10),
  addRarity('rare', 10, 40),
  addRarity('original', 40, 100)
];
 ``` 
from 1 to 10 will be super rare – 10 images
from 10 to 40 will be rare – 30 images
from 40 to 100 will be original – 60 images

~~Maybe another detail: by changing the order of `addRarity` you can control if the first x to y is a certain rarity. Mind that it is inverted though. In the above example the last 10 images will be super_rare in the output folder.~~

**Comment by JimFit77** [comment]
> > I think I figured it out.
> > Go to config.js
> > Then to line 129: const editionSize = 10;
> > Change the number to the total number of NFT's you want to generate.
> > Then make sure to adjust your rarities.
> > You can do this starting on line 135 and ending on line 138:
> > let rarityWeights = [
> > addRarity('super_rare', 1, 1),
> > addRarity('rare', 2, 5),
> > addRarity('original', 5, 10)
> > Adjust the numbers so the rarities match the total number of NFT's you want to create.
> > Let me know if this helps. I was running the code and it would only create 10 editions. After doing some digging I figured it out and was able to do 15 editions without an error.
> 
> After playing with numbers, I got it to work for a bit, and then it gave me an infinite loop.


I still get errors, first of all const editionSize doesn't exist in line 129 but in line 9, where should i put it? Where should i paste the rest of the text? There is no 



> const editionSize = 100;
> 
> let rarityWeights = [
>   addRarity('super_rare', 1, 10),
>   addRarity('rare', 10, 40),
>   addRarity('original', 40, 100)
> ];

Hey @WalkingEclipse 

It doesn't work for me :(

My const editionSize is on line 9 NOT line 129, should i change something here? also there are i cannot find these lines, should i add them somewhere?

let rarityWeights = [
  addRarity('super_rare', 1, 10),
  addRarity('rare', 10, 40),
  addRarity('original', 40, 100)
];


![sdgdfgdgdfgdfd](https://user-images.githubusercontent.com/94700752/142652160-858f27b7-4614-40f8-b72a-a48130b87e9e.JPG)

**Comment by JimFit77** [comment]
how i remove numbers from the final image? also how i surpass infinite loop?
